=== EBSI-umontreal/inu3011-publication-BD-XML/src/DTD/fiche-poisson.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Modèle XML développé dans le cadre du cours INU3011 Documents structurés -->
<!-- EBSI - Université de Montréal -->

<!-- Équipe: Marilou Bourque (auxiliaire), Arnaud D’Alayer (auxiliaire), Yves Marcoux (professeur). -->
<!-- Élément de plus haut niveau: fiche-poisson -->

<!--
Les commentaires commençant par "doc:" sont utilisés par oXygen comme documentation d’aide à la
saisie. Ils sont affichés en infobulles pendant l’édition de documents conformes à la DTD lorsque le
curseur survole un nom d’élément ou d’attribut.
-->

<!-- Modèle de contenu correspondant à la mesure d’une certaine caractéristique
        physique d’un poisson. -->
<!ENTITY % moyMinMaxComm "((
(moy, min?, max?) | (min, max?) | max
), commentaires?)">

<!-- Modèle de contenu de texte structuré en sections ou en paragraphes. -->
<!ENTITY % texte "(section+ | para+)">

<!-- Modèle de contenu de texte rendu en un seul paragraphe. -->
<!ENTITY % inline "(#PCDATA | lien | tempé-C | long-cm | vol-litres | em)*">

<!-- doc: Une fiche descriptive d’une espèce de poisson d’aquariophilie. -->
<!ELEMENT fiche-poisson (métadonnées, poisson)>

<!-- doc: L’identifiant de la fiche, soit son nom de fichier, sans l’extension ".xml". Exemples:
  cyprinus_carpio
  poissonus_panus -->
<!ATTLIST fiche-poisson id NMTOKEN #REQUIRED>

<!-- doc: Indique si une photo du poisson est disponible ou non dans le dossier des photos. -->
<!ATTLIST fiche-poisson image (oui | non) #REQUIRED>

<!-- doc: Les métadonnées de gestion de la fiche. -->
<!ELEMENT métadonnées (date-dern-modif, créateur+)>

<!-- doc: L’information descriptive proprement dite de l’espèce de poisson. -->
<!ELEMENT poisson (noms, famille, origines-géo, première-description?, taille-cm?,
longévité-ans?, qualité-eau?, zone-de-vie?, alimentation?, aspect-physique?, dimorphisme?,
comportement?, reproduction?)>

<!-- doc: Date de création ou de dernière modification de la fiche; forme AAA-MM-JJ. Exemples:
  2018-09-30
  2021-12-01 -->
<!ELEMENT date-dern-modif (#PCDATA)>

<!-- doc: Nom d’une personne ayant contribué au contenu de la fiche; forme Prénom Nom-de-famille. Un élément "créateur" par contributeur. Exemples:
  Jacques A. Le Maître
  Lam Locong -->
<!ELEMENT créateur (#PCDATA)>

<!-- doc: Les différents noms sous lesquels l’espèce de poisson est connue. -->
<!ELEMENT noms (nom-scientifique, nom-commun*)>

<!-- doc: Nom scientifique de l’espèce (habituellement un nom latin en deux mots). Inscrit avec majuscule initiale. Exemples:
  Cyprinus carpio
  Acanthicus adonis -->
<!ELEMENT nom-scientifique (#PCDATA)>

<!-- doc: Un nom populaire, en français ou en anglais, sous lequel l’espèce est connue. Inscrit avec majuscule initiale au premier mot seulement. Exemples:
  Carpe commune
  Adonis pleco -->
<!ELEMENT nom-commun (#PCDATA)>

<!-- doc: Indique si le nom est en français (fr) ou en anglais (en). -->
<!ATTLIST nom-commun langue (fr | en) #REQUIRED>

<!-- doc: Nom de la famille à laquelle l’espèce appartient. Habituellement un nom français au pluriel. Inscrit avec majuscule initiale. Exemples:
  Cyprinidés
  Ascanidés -->
<!ELEMENT famille (#PCDATA)>

<!-- doc: Régions où l’on trouve l’espèce à l’état naturel. -->
<!ELEMENT origines-géo (origine+, commentaires?)>

<!-- doc: Une des origines géographiques de l’espèce. Si possible, utiliser une forme provenant d’un thésaurus géographique. Exemples:
  Amérique du Sud - Uruguay - Río Negro
  Australie - Queensland -->
<!ELEMENT origine (#PCDATA)>

<!-- doc: Première description scientifique de l’espèce. -->
<!ELEMENT première-description (nom-du-descripteur, année)>

<!-- doc: Nom de famille de la ou des personnes ayant décrit l’espèce pour la première fois. Si plus d’un nom, les séparer par "&amp;". Exemples:
  Isbrücker &amp; Nijssen
  Linnaeus -->
<!ELEMENT nom-du-descripteur (#PCDATA)>

<!-- doc: Année où l’espèce a été décrite pour la première fois. Exemples:
  1926
  2000 -->
<!ELEMENT année (#PCDATA)>

<!-- doc: Longueur, en centimètres, des individus de cette espèce. Exemples:
  <mâle><moy>20</moy></mâle><femelle><moy>15</moy></femelle>
  <min>43,5</min><max>55,6</max><commentaires>n=7</commentaires> -->
<!ELEMENT taille-cm ((mâle, femelle)|(%moyMinMaxComm;))>

<!-- doc: L’espérance de vie des individus de cette espèce. -->
<!ELEMENT longévité-ans (%moyMinMaxComm;)>

<!-- doc: Bloc de texte consistant en un titre suivi d'un paragraphe ou plus. -->
<!ELEMENT section (titre, para+)>

<!-- doc: Titre d’une section. Exemples:
  Approche générale
  Conseils pour les débutants -->
<!ELEMENT titre (#PCDATA)>

<!-- doc: Un paragraphe de texte. Peut contenir du texte et les sous-éléments suivants:
  - em          passage en emphase;
  - lien        lien vers autre fiche;
  - tempé-C     température (en °C);
  - long-cm     longueur (en cm);
  - vol-litres  volume (en litres). Exemples:
  Tous les spécimens ont survécu.
  La température atteint rarement <tempé-C>42</tempé-C>.
  C’est <em>inouï</em>. -->
<!ELEMENT para %inline;>

<!-- doc: Un passage en emphase dans un paragraphe. Peut contenir du texte et les sous-éléments suivants:
  - em          passage (encore plus) en emphase;
  - lien        lien vers autre fiche;
  - tempé-C     température (en °C);
  - long-cm     longueur (en cm);
  - vol-litres  volume (en litres). Exemples:
  plus grand que <lien id="cyprinus_carpio">Cyprinus carpio</lien>!
  <long-cm>10</long-cm> de moins…
  beaucoup <em>beaucoup</em> plus grand! -->
<!ELEMENT em %inline;>

<!-- doc: Un lien vers une autre fiche. L’attribut "id" donne l’identifiant de la fiche cible, soit le nom de fichier de la fiche, sans l’extension ".xml". On doit inscrire comme contenu de l'élément le nom scientifique contenu dans la fiche cible. Exemples:
  Cyprinus carpio
  Acanthicus adonis -->
<!ELEMENT lien (#PCDATA)>

<!-- doc: Identifiant de la fiche cible, soit le nom de fichier de la fiche, sans l’extension ".xml". Exemples:
  cyprinus_carpio
  paracheirodon_axelrodi -->
<!ATTLIST lien id NMTOKEN #REQUIRED>

<!-- doc: Une température, en degrés Celsius. Inscrire une valeur numérique seule, sans le mot "degrés". Exemples:
  34,7
  -2,45
  0 -->
<!ELEMENT tempé-C (#PCDATA)>

<!-- doc: Une longueur, en centimètres. Inscrire une valeur numérique seule, sans le mot "centimètres". Exemples:
  23
  40,6 -->
<!ELEMENT long-cm (#PCDATA)>

<!-- doc: Un volume, en litres. Inscrire une valeur numérique seule, sans le mot "litres". Exemples:
  248
  0,983 -->
<!ELEMENT vol-litres (#PCDATA)>

<!-- doc: Caractéristiques de l’eau convenant à cette espèce. -->
<!ELEMENT qualité-eau (température-C, acidité-pH?, dureté-dGH?)>

<!-- doc: Température acceptable de l’eau (degrés Celsius). -->
<!ELEMENT température-C (%moyMinMaxComm;)>

<!-- doc: Acidité acceptable de l’eau (pH). -->
<!ELEMENT acidité-pH (%moyMinMaxComm;)>

<!-- doc: Dureté acceptable de l’eau (dGH). -->
<!ELEMENT dureté-dGH (%moyMinMaxComm;)>

<!-- doc: Indication de la profondeur où l’on trouve habituellement l’espèce. Exemples:
  Fond
  Milieu et inférieure
  Surface et milieu
  Inférieure -->
<!ELEMENT zone-de-vie (#PCDATA)>

<!-- doc: Informations, en format libre, concernant l’alimentation de cette espèce. -->
<!ELEMENT alimentation (%texte;)>

<!-- doc: Informations, en format libre, concernant l’aspect physique de cette espèce. -->
<!ELEMENT aspect-physique (%texte;)>

<!-- doc: Informations, en format libre, concernant le dimorphisme (différences entre mâles et femelles) de cette espèce. -->
<!ELEMENT dimorphisme (%texte;)>

<!-- doc: Informations, en format libre, concernant le comportement de cette espèce. -->
<!ELEMENT comportement (%texte;)>

<!-- doc: Informations, en format libre, concernant la reproduction de cette espèce. -->
<!ELEMENT reproduction (%texte;)>

<!-- doc: Longueur, en centimètres, des individus mâles de cette espèce. -->
<!ELEMENT mâle (%moyMinMaxComm;)>

<!-- doc: Longueur, en centimètres, des individus femelles de cette espèce. -->
<!ELEMENT femelle (%moyMinMaxComm;)>

<!-- doc: Un paragraphe ou plus de commentaires en format libre se rapportant à l’élément où ces commentaires se trouvent. -->
<!ELEMENT commentaires (para+)>

<!-- doc: Valeur numérique correspondant à la valeur moyenne d’une mesure. Ne pas inscrire le nom de l’unité. Exemples:
  45,987
  17
  0,52 -->
<!ELEMENT moy (#PCDATA)>

<!-- doc: Valeur numérique correspondant à la valeur maximum d’une mesure. Ne pas inscrire le nom de l’unité. Exemples:
  45,987
  17
  0,52 -->
<!ELEMENT max (#PCDATA)>

<!-- doc: Valeur numérique correspondant à la valeur minimum d’une mesure. Ne pas inscrire le nom de l’unité. Exemples:
  45,987
  17
  0,52 -->
<!ELEMENT min (#PCDATA)>

=== EBSI-umontreal/inu3011-publication-BD-XML/src/XML/cyprinus_carpio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/XHTML.xsl"?>
<!DOCTYPE fiche-poisson SYSTEM "../DTD/fiche-poisson.dtd" >
<fiche-poisson image="oui" id="cyprinus_carpio">
  <métadonnées>
    <date-dern-modif>2016-03-28</date-dern-modif>
    <créateur>Marina-Océane Poisson-Doré</créateur>
    <créateur>Yves Marcoux</créateur>
  </métadonnées>
  <poisson>
    <noms>
      <nom-scientifique>Cyprinus carpio</nom-scientifique>
    </noms>
    <famille>Cyprinidés</famille>
    <origines-géo>
      <origine>États-Unis d’Amérique</origine>
    </origines-géo>
  </poisson>
</fiche-poisson>

=== EBSI-umontreal/inu3011-publication-BD-XML/src/XML/aborichthys_elongatus.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/XHTML.xsl"?>
<!DOCTYPE fiche-poisson SYSTEM "../DTD/fiche-poisson.dtd" >
<fiche-poisson id="aborichthys_elongatus" image="non">
  <métadonnées>
    <date-dern-modif>2019-03-28</date-dern-modif>
    <créateur>Yves Marcoux</créateur>
  </métadonnées>
  <poisson>
    <noms>
      <nom-scientifique>Aborichthys elongatus</nom-scientifique>
    </noms>
    <famille>Hilaridés</famille>
    <origines-géo>
      <origine>Inde (Bengale occidental, Darjeeling)</origine>
      <origine>Bangladesh</origine>
    </origines-géo>
    <première-description>
      <nom-du-descripteur>Hora</nom-du-descripteur>
      <année>1921</année>
    </première-description>
    <taille-cm>
      <mâle>
        <moy>9</moy>
      </mâle>
      <femelle>
        <min>12</min>
        <max>15</max>
      </femelle>
    </taille-cm>
    <longévité-ans>
      <min>6</min>
      <max>8</max>
    </longévité-ans>
    <qualité-eau>
      <température-C>
        <min>27</min>
        <max>30</max>
      </température-C>
      <acidité-pH>
        <min>6,5</min>
        <max>7,5</max>
      </acidité-pH>
      <dureté-dGH>
        <min>5</min>
        <max>12</max>
      </dureté-dGH>
    </qualité-eau>
    <zone-de-vie>Fond</zone-de-vie>
    <alimentation>
      <para>Comme les spécimens disponibles dans le commerce sont sauvages, il faudra probablement
        leur proposer des aliments vivants puis essayer de les habituer aux congelés et nourritures
        sèches progressivement.</para>
    </alimentation>
    <aspect-physique>
      <para>Longiforme, corps gris à doré, queue rouge (plus ou moins prononcé). Des bandes claires
        apparaissent sur la fin du corps et sur la queue. Barbillons autours de la bouche.</para>
    </aspect-physique>
    <dimorphisme>
      <para>Les femelles ont un embonpoint plus prononcé que les mâles et ont plus de marques sur le
        corps et moins sur la queue.</para>
    </dimorphisme>
    <comportement>
      <para>Aborichthys elongatus étant originaire de torrents et rivières à fort courant,
        l&#8217;aquarium doit reproduire ces conditions car ces poissons ont des exigences élevées
        en oxygène. Donnez-lui beaucoup de cachettes sous des cailloux aplatis. Attention, cette
        espèce peut être à la fois divertissante et frustrante. Ces loches sont des chercheuses
        chevronnées et aiment fouiller partout pour se cacher sous le décor. Leurs fouilles peuvent
        être très perturbatrices pour l&#8217;aspect esthétique d&#8217;un aquarium. Veillez à ce
        que tous les décors soient solidement installés car il est tout à fait possible que ces
        poissons déséquilibrent durant leurs fouilles une pile instable de roche et provoquer ainsi
        un effondrement qui pourrait être désastreux.</para>
      <para>Très vorace, Aborichthys elongatus entre en frénésie à chaque séance de nourrissage. Il
        dévore alors tout ce qui ressemble un tant soit peu à de la nourriture. Peu difficile, il
        accepte tout type de nourriture, et n&#8217;hésite pas à aller chercher des flocons en
        surface.</para>
      <para>Sociable, Aborichthys elongatus accepte sans souci la présence de congénères, parfois
        dans le même terrier. Néanmoins, il arrive que des mâles se battent pour un territoire, mais
        bien souvent, ils partagent à nouveau leur cachette dès le lendemain.</para>
      <para>Aborichthys elongatus cohabite parfaitement avec les Gastromyzon, dont les
        caractéristiques de maintenance sont très proches.</para>
      <para>L&#8217;essentiel des autres habitants de l&#8217;aquarium est totalement ignoré. </para>
      <para>Très divertissant, ces poissons sont faciles à maintenir si les conditions de vie sont
        un minimum respectées. Un climat tempéré avec une température moyenne de
        <tempé-C>30,5</tempé-C> est idéal.</para>
    </comportement>
    <reproduction>
      <para>Selon Joseph Schwanka, le croisement avec l&#8217;<lien
        id="acanthurus_lineatus">Acanthurus lineatus</lien> est
        monnaie courante dans les aquariums de Monaco. Il faudrait cependant plus de
        <vol-litres>800</vol-litres> d&#8217;eau (<em>eh oui, <vol-litres>800</vol-litres> !</em>)
        pour que l&#8217;opération réussisse.</para>
    </reproduction>
  </poisson>
</fiche-poisson>
